export const ADD_TO_CART_REQUEST = 'ADD_TO_CART_REQUEST'
export const ADD_TO_CART_SUCCESS = 'ADD_TO_CART_SUCCESS'
export const ADD_TO_CART_ERR = 'ADD_TO_CART_ERR'

export const GET_CART_REQUEST = 'GET_CART_REQUEST'
export const GET_CART_SUCCESS = 'GET_CART_SUCCESS'
export const GET_CART_ERR = 'GET_CART_SUCCESS'

export const REMOVE_CART_REQUEST = 'REMOVE_CART_REQUEST'
export const REMOVE_CART_SUCCESS = 'REMOVE_CART_SUCCESS'
export const REMOVE_CART_ERR = 'REMOVE_CART_ERR'